### ISSUE TITLE
Add constinit to c++20

### ISSUE THREAD

**Issue by sobieh** [AnthonyCalandra/modern-cpp-features#104]
There is constexpr, consteval but constinit is not described.
It could be worth to add it.

**Comment by rajkumarananthu** [comment]
Can I take this and do the necessary documentation for "constinit"?

**Comment by AnthonyCalandra** [comment]
Yes, feel free. :)

**Comment by rajkumarananthu** [comment]
Hi @AnthonyCalandra I have created a pull request to this addition: https://github.com/AnthonyCalandra/modern-cpp-features/pull/110

Please review it and accept the same.
Thanks
Rajkumar Ananthu.

**Comment by AnthonyCalandra** [comment]
Done https://github.com/AnthonyCalandra/modern-cpp-features/commit/e2f9058ca7961fb97b1f4308256ca8d61107a9b9
