### ISSUE TITLE
fallthrough example is misleading. c++17

### ISSUE THREAD

**Issue by clepz** [AnthonyCalandra/modern-cpp-features#114]
Hi.

fallthrough example in the [section](https://github.com/AnthonyCalandra/modern-cpp-features#fallthrough-nodiscard-maybe_unused-attributes) is misleading.

Look at the explanation in the [link](https://en.cppreference.com/w/cpp/language/attributes/fallthrough):

> May only be applied to a [null statement](https://en.cppreference.com/w/cpp/language/statements#Expression_statements) to create a fallthrough statement ([[fallthrough]];).
> 
> A fallthrough statement may only be used in a [switch](https://en.cppreference.com/w/cpp/language/switch) statement, where the next statement to be executed is a statement with a case or default label for that switch statement.

The example is not compilable in its current state.

**Comment by AnthonyCalandra** [comment]
Thanks, this is indeed a bit misleading. Marking this as a bug.

**Comment by clepz** [comment]
Hi. I opened a [pr](https://github.com/AnthonyCalandra/modern-cpp-features/pull/115).
