### ISSUE TITLE
Is C++20 section missing __VA_OPT language attribute for better support of variadic macros?

### ISSUE THREAD

**Issue by zzombie** [AnthonyCalandra/modern-cpp-features#119]
Is C++20 section missing __VA_OPT language attribute for better support of variadic macros? e.g., some detailed usage outlined here 
https://www.scs.stanford.edu/~dm/blog/va-opt.html

**Comment by AnthonyCalandra** [comment]
Added in commit 052c3d80bfe51253d2e74e8d6bdb294397bb7128
