### ISSUE TITLE
decltype(auto) issue

### ISSUE THREAD

**Issue by todatamining** [AnthonyCalandra/modern-cpp-features#12]
const int x = 0;
auto x1 = x; // int
decltype(auto) x2 = x; // const int
int y = 0;
int& y1 = y;
auto y2 = y; // int
decltype(auto) y3 = y; // int&   <--------------this should be decltype(auto) y3 = **y1;** right?
int&& z = 0;
auto z1 = std::move(z); // int
decltype(auto) z2 = std::move(z); // int&&

**Comment by AnthonyCalandra** [comment]
Correct! I'll fix this typo and push it up. Thank you.
