### ISSUE TITLE
std::span 2nd example does not compile

### ISSUE THREAD

**Issue by zzombie** [AnthonyCalandra/modern-cpp-features#120]
Original example snap from std::span section 
+++++++++++++++++++++++++++++++++
constexpr size_t LENGTH_ELEMENTS = 3;
int* arr = new int[LENGTH_ELEMENTS]; // arr = {0, 0, 0}

// Fixed-sized span which provides a view of `arr`.
std::span<int, LENGTH_ELEMENTS> span = arr;
span[1] = 1; // arr = {0, 1, 0}
+++++++++++++++++++++++++++++++++

A small test in C++20 compatible compiler throws conversion type mismatch error
++++++++++++++++++++++++++++++++++
└─$ cat span_test.cpp
#include <iostream>
#include <span>
#include <new>

int main()
{
        constexpr size_t ARR_SIZE = 4;
        int* arr = new int[ARR_SIZE];

        std::span<int, ARR_SIZE> sp = arr;

}

┌──(suaich㉿Suva-Laptop)-[~/cpp/C++20/span]
└─$ g++ -std=c++2b span_test.cpp
span_test.cpp: In function ‘int main()’:
span_test.cpp:10:39: error: conversion from ‘int*’ to non-scalar type ‘std::span<int, 4>’ requested
   10 |         std::span<int, ARR_SIZE> sp = arr;
      |                                       ^~~

┌──(suaich㉿Suva-Laptop)-[~/cpp/C++20/span]
└─$
++++++++++++++++++++++++++++++++++

**Comment by AnthonyCalandra** [comment]
Thanks looks like this is a bug with the example. I'm probably going to rewrite a part of this section to make the examples better.

For now, here's a version of the example that compiles on clang and gcc:
```cpp
constexpr size_t LENGTH_ELEMENTS = 3;
int* arr = new int[LENGTH_ELEMENTS]; // arr = {0, 0, 0}

// Fixed-sized span which provides a view of `arr`.
std::span<int, LENGTH_ELEMENTS> span{ arr, LENGTH_ELEMENTS };
span[1] = 1; // arr = {0, 1, 0}

// Dynamic-sized span which provides a view of `arr`.
std::span<int> d_span{ arr, LENGTH_ELEMENTS };
span[0] = 1; // arr = {1, 1, 0}
```

**Comment by AnthonyCalandra** [comment]
Hopefully the new section is more intuitive: https://github.com/AnthonyCalandra/modern-cpp-features/commit/8183b4bbdbc1fcf122aae9e06bdf0224310fb4f7

Let me know if it could be improved further.
