### ISSUE TITLE
std::bind_front, std::bind_back, version header introduced in C++20 not mentioned

### ISSUE THREAD

**Issue by zzombie** [AnthonyCalandra/modern-cpp-features#122]
https://en.cppreference.com/w/cpp/utility/functional/bind_front

https://en.cppreference.com/w/cpp/header/version

**Comment by Siddharthgupta007** [comment]
hey , how can I help you in this project issue.

**Comment by AnthonyCalandra** [comment]
Just completed `std::bind_front`and I won't do the version header because I think it's really only useful for library authors. `std::bind_back` will come as part of my update for C++23.
