### ISSUE TITLE
std::to_address to convert a pointer to raw pointer and smart pointer default initialization in C++20 missed

### ISSUE THREAD

**Issue by zzombie** [AnthonyCalandra/modern-cpp-features#124]
https://en.cppreference.com/w/cpp/memory/to_address

**Comment by AnthonyCalandra** [comment]
I think with your second point you're referring to the make_overwrite versions of the smart pointer make_* functions? To be honest I think both of these features are too niche to include in the sheet so I'm going to close this one unless I get enough requests for it.
