### ISSUE TITLE
"Class types in non-type template parameters" example doesn't compile

### ISSUE THREAD

**Issue by kasparthommen** [AnthonyCalandra/modern-cpp-features#130]
This example doesn't compile:

https://github.com/AnthonyCalandra/modern-cpp-features#class-types-in-non-type-template-parameters

See here:

https://godbolt.org/z/sf6hKPPso

**Comment by AnthonyCalandra** [comment]
Thanks for the report! You're right, the example doesn't compile, and I think it could benefit from a better example. I'll add it to the TODO list.

**Comment by AnthonyCalandra** [comment]
Fixed in 4d2f4d4329209b304fb49ac7b476cd836fcab443
