### ISSUE TITLE
Would be nice to include the new rounding functions in chrono in C++17

### ISSUE THREAD

**Issue by UPC-PaalDriveklepp** [AnthonyCalandra/modern-cpp-features#132]
floor(std::chrono::duration)(C++17) | converts a duration to another, rounding down(function template)
-- | --
ceil(std::chrono::duration)(C++17) | converts a duration to another, rounding up(function template)
round(std::chrono::duration)(C++17) | converts a duration to another, rounding to nearest, ties to even(function template)
abs(std::chrono::duration)(C++17) | obtains the absolute value of the duration(function template)

[floor(std::chrono::duration)](https://en.cppreference.com/w/cpp/chrono/duration/floor)
  
(C++17)
 
converts a duration to another, rounding down
(function template)
[ceil(std::chrono::duration)](https://en.cppreference.com/w/cpp/chrono/duration/ceil)
  
(C++17)
 
converts a duration to another, rounding up
(function template)
[round(std::chrono::duration)](https://en.cppreference.com/w/cpp/chrono/duration/round)
  
(C++17)
 
converts a duration to another, rounding to nearest, ties to even
(function template)
[abs(std::chrono::duration)](https://en.cppreference.com/w/cpp/chrono/duration/abs)
  
(C++17)
 
obtains the absolute value of the duration
(function template)

**Comment by AnthonyCalandra** [comment]
Added in commit 3f054364ad8636a72cf8c9ef15e0b0457865bf44
