### ISSUE TITLE
generator<T> is C++23, not C++20

### ISSUE THREAD

**Issue by jwezel** [AnthonyCalandra/modern-cpp-features#133]
I saw that in the _coroutine_ chapter in the section _C++20_, as an example, the `generator<T>` type was used, but this is only available as of C++23.

**Comment by AnthonyCalandra** [comment]
I make a note at the bottom of the chapter mentioning this but maybe I should move it to the top instead:

> Note: While these examples illustrate how to use coroutines at a basic level, there is lots more going on when the code is compiled. These examples are not meant to be complete coverage of C++20's coroutines. Since the generator and task classes are not provided by the standard library yet, I used the cppcoro library to compile these examples.

**Comment by AnthonyCalandra** [comment]
Fixed in commit 452a63bd906ad767d38f97fa33b8e0e71089cf26
