### ISSUE TITLE
CPP20 constinit: `g` is not constexpr typo

### ISSUE THREAD

**Issue by jonathanbcarlson** [AnthonyCalandra/modern-cpp-features#134]
In the `constinit` example in [CPP20.md](https://github.com/AnthonyCalandra/modern-cpp-features/blob/1284ccd3cfee85f0ce2f477df41cb43033bc4429/CPP20.md#constinit):
```cc
const char* g() { return "dynamic initialization"; }
constexpr const char* f(bool p) { return p ? "constant initializer" : g(); }

constinit const char* c = f(true); // OK
constinit const char* d = f(false); // ERROR: `g` is not constexpr, so `d` cannot be evaluated at compile-time.
```
it has `d = f(false)` when it should be `d = g(false)`.

Thanks for all the work on this wonderful cheatsheet!

**Comment by AnthonyCalandra** [comment]
Thanks for the bug report! Done
