### ISSUE TITLE
Acknowledgements to Thomas Beckers - Link is dead

### ISSUE THREAD

**Issue by stho** [AnthonyCalandra/modern-cpp-features#135]
I just clicked on one of the acknowledgements [links](http://thbecker.net/articles/rvalue_references/section_01.html) and it seems to be dead. I just found a pdf version [here](https://github.com/AnthonyCalandra/modern-cpp-features/blob/master/CPP20.md#acknowledgements), but wasn't able to finde the original page.

@thbecker did you move the site?

**Comment by AnthonyCalandra** [comment]
Wow looks like the site isn't available anymore 😥 too bad the resource was really awesome.

**Comment by stho** [comment]
Yeah, is there any backup available?

**Comment by AnthonyCalandra** [comment]
> Yeah, is there any backup available?

It's probably somewhere living in the internet archive. If you submit a PR I'll merge it in otherwise I'll make this a TODO item.

**Comment by AnthonyCalandra** [comment]
Fixed in commit 3ca9ac130d61c0c0fecaba0d2c2897562ccfab07
