### ISSUE TITLE
my_integer_sequence

### ISSUE THREAD

**Issue by rpuntaie** [AnthonyCalandra/modern-cpp-features#19]
What would the definition of 

`my_integer_sequence`

be?

**Comment by AnthonyCalandra** [comment]
Looks like I forgot to add the definition of what a `my_integer_sequence` would look like when using that feature. I've added in this commit: https://github.com/AnthonyCalandra/modern-cpp-features/commit/b887e0eb5572885c8ccf3b5df89ea494afa88590.
