### ISSUE TITLE
Descriptions on std::make_shared<T> and std::make_unique<T>

### ISSUE THREAD

**Issue by conz27** [AnthonyCalandra/modern-cpp-features#22]
With C++11/14, you have the ability to create `std::shared_ptr<T>` and `std::unique_ptr<T>` smart pointers with `std::make_shared<T>` and `std::make_unique<T>` respectively.

There are some important differences when creating these pointers using their constructors vs. make_XXX<T> equivalents in the way they are allocated.

Might be worthwhile adding a blurb about on scenarios where one is preferred over the other and the gotchas involved. Subtle differences that most people won't pick-up on, but still important to be aware of.

**Comment by AnthonyCalandra** [comment]
Done. https://github.com/AnthonyCalandra/modern-cpp-features/commit/543545ca9c650ddcf396b2dd59e4a3d1f425c4d9

If I'm missing anything feel free to let me know.
