### ISSUE TITLE
Typo on fold expression?

### ISSUE THREAD

**Issue by candychiu** [AnthonyCalandra/modern-cpp-features#30]
e1 op1 ... op2 e2

According to http://en.cppreference.com/w/cpp/language/fold, op1 and op2 should be the same.  Is this a typo or a new feature?

**Comment by AnthonyCalandra** [comment]
Yes, I believe you are correct. I'll fix this up when I get a chance.

**Comment by AnthonyCalandra** [comment]
Merged. db43d4b9c630bb2caa11e555a75e4125661d8bd1
