### ISSUE TITLE
Missing features like [[attributes]]

### ISSUE THREAD

**Issue by Alkenso** [AnthonyCalandra/modern-cpp-features#44]
There are set of attributes coming with the latest C++ standard like [[nodiscard]], [[maybe_unused]], and [[fallthrough]].
Consider to add them into your beautiful docs.

**Comment by AnthonyCalandra** [comment]
Sorry for the late response but I'll get these in eventually!

**Comment by tupaschoal** [comment]
I've written some PRs to improve the attributes explanation
