### ISSUE TITLE
unexplained universal reference in introduction to rvalue references

### ISSUE THREAD

**Issue by sapientN3T** [AnthonyCalandra/modern-cpp-features#45]
https://github.com/AnthonyCalandra/modern-cpp-features/blob/master/CPP11.md#rvalue-references

```
    auto&& al2 = x; // `al2` is an lvalue of type `int&`
```

Since x is an L-value, I had assumed it should cause a compiler error, just as the line above it did: 
```
    int&& xr = x; // compiler error -- `x` is an lvalue
````

But it seems that the compiler silently consumes the extra & if it is auto!?

I had to log onto freenode chat and ask someone about this, because it appeared to be an error in the tutorial. They explained to me that this is a separate concept known as a Universal Reference.

https://isocpp.org/blog/2012/11/universal-references-in-c11-scott-meyers

You should at least make mention of the concept at that point so that it becomes clear what is happening. Even better, with hyperlink to detailed explanation.

**Comment by AnthonyCalandra** [comment]
Sure, I'll add this to the TODO list.

**Comment by AnthonyCalandra** [comment]
This new section and the other relevant sections were definitely in need of an overhaul. So I've made a few changes that I merged in here: https://github.com/AnthonyCalandra/modern-cpp-features/commit/dff069e9f56872f2a260e60c5285296af0bef805. If you have suggestions or catch an error feel free to re-open the issue.
