### ISSUE TITLE
Missing feature std::async

### ISSUE THREAD

**Issue by defmys** [AnthonyCalandra/modern-cpp-features#46]
C++11 feature **std::async** is missing.

See [https://en.cppreference.com/w/cpp/thread/async](https://en.cppreference.com/w/cpp/thread/async)

**Comment by AnthonyCalandra** [comment]
https://github.com/AnthonyCalandra/modern-cpp-features/commit/4df2261e0c0dbee7770fd37ec2f543013746f014 🎉
