### ISSUE TITLE
[Q] c++ 20?

### ISSUE THREAD

**Issue by kcris** [AnthonyCalandra/modern-cpp-features#53]
Hi, 
First of all, great work, thank you so much!
Second: any plans to maintain this for c++20 or future releases?
thanks
Chris

**Comment by AnthonyCalandra** [comment]
Hi Chris, the goal is indeed to maintain this for C++20. I've got a busy year ahead of me as you can tell! 😬

**Comment by kcris** [comment]
this repo is a very cool idea, a very short and pragmatic approach, yet full of useful information. Thanks a lot!!
