### ISSUE TITLE
Ref-qualified member functions

### ISSUE THREAD

**Issue by paul-j-lucas** [AnthonyCalandra/modern-cpp-features#54]
Member functions like:
```
struct S {
    void f1() &;
    void f2() &&;
    void f3() const &;
    void f4() const &&;
};
```
are missing.

**Comment by AnthonyCalandra** [comment]
Resolved by https://github.com/AnthonyCalandra/modern-cpp-features/commit/1a5af17e8ac3d0399f3ea63f207e0517762e72a0.
