### ISSUE TITLE
C++ 11 Feature Missing - Trailing return type

### ISSUE THREAD

**Issue by kennycastro007** [AnthonyCalandra/modern-cpp-features#55]
In the C++ 11 Language features, Function Trailing Return Types isn't in the list.
According to https://en.cppreference.com/w/cpp/language/functions, this is a feature in C++ 11, and helps with writing arguably more readable code.

**Comment by AnthonyCalandra** [comment]
Resolved by https://github.com/AnthonyCalandra/modern-cpp-features/commit/1c60839a11010e214131d057b980f4873bcbe0e6.
