### ISSUE TITLE
Missing type aliases using `using`

### ISSUE THREAD

**Issue by AnthonyCalandra** [AnthonyCalandra/modern-cpp-features#58]
Title.

**Comment by ABham2997** [comment]
Type aliases are already included in the CPP11.md file under the header "template aliases"? They do, however, need to be renamed to "type aliases" as "template aliases" in an incorrect label.

**Comment by AnthonyCalandra** [comment]
@ABham2997 Yes I agree; the bad labelling was why I couldn't find them!

**Comment by AnthonyCalandra** [comment]
https://github.com/AnthonyCalandra/modern-cpp-features/commit/af7125a698913c87436e91f3288bc57b4eacc9b5
