### ISSUE TITLE
References to WG21 papers for each feature

### ISSUE THREAD

**Issue by solodon4** [AnthonyCalandra/modern-cpp-features#6]
Great summary! Thanks! It would be even better if you would include references to WG21 papers (final version) describing that specific language or library feature. Symbolic references to the standard sections a la [stmt.if] would be great too.

**Comment by AnthonyCalandra** [comment]
I decided I didn't want to do this for two reasons:
* Some of these features come as a result of multiple papers. e.g. The [rvalue references](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2006/n2118.html) paper I took from clang's site references N1952, and N1855. Also, rvalue references for `*this` is in a separate paper [here](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2439.htm) which references N2377 and N1821 (and maybe more but I gave up at this point). This is a mess I'd prefer to avoid.
* Adding references to these sections won't provide value to someone wanting to get a quick dose of what the feature does and why it's useful. I think if they really need to understand how the feature works from a technical standpoint they'd need to spend some time reading the paper(s).

Thoughts?

**Comment by NewProggie** [comment]
Honestly, I don't get your point. Adding useful information, which doesn't clutter the feature overview list would be a no-brainer for me. This 'someone' is not supposed to click on all those reference links, if he just wants to get a quick overview.

I was planning to add some more references such as CMAKE_CXX_KNOWN_FEATURES for the specific C++ features, as it might come in handy for developers working with CMake and C++. If you want to keep your document plain and simple, I'm fine with that. I will just fork this repo and add all the things I think are useful.

**Comment by AnthonyCalandra** [comment]
> If you want to keep your document plain and simple
This is my point.
