### ISSUE TITLE
Inline static members

### ISSUE THREAD

**Issue by AnthonyCalandra** [AnthonyCalandra/modern-cpp-features#74]
Include an example of inline static members in the "Inline variables" section.

**Comment by tawmoto** [comment]
Thank you for tooking my suggestion into consideration.
I think that the inline static is a great addition to C++17, instead of declaring the static variable in 2 places.

**Comment by AnthonyCalandra** [comment]
Merged. https://github.com/AnthonyCalandra/modern-cpp-features/pull/77
