### ISSUE TITLE
Raw string literals missing from C++11 feature list

### ISSUE THREAD

**Issue by galkinvv** [AnthonyCalandra/modern-cpp-features#75]
The doc is great! Hoewever some areas are still missing.
C++11 intoduced raw string literals: https://en.cppreference.com/w/cpp/language/string_literal

It is useful in many different areas, like strings with quotes, multiline strings and for example windows paths without escaping backslashes:

```c++
const char win_path[] = R"(c:\some\unescaped\path)";
```

The same cppreference link also mentions u8/u16/u32 literals, but I'm not sure that their addition is major enough to include in a high-level list.

**Comment by DaveUltra** [comment]
Hi! I know this issue's been open for more than a year now. But I came across here as a new contributor who wanted to give a first try at contributing to an open-source project, without having to do incredibly complex tasks. If you want I can try to add documentation on raw string literals...

**Comment by AnthonyCalandra** [comment]
Hi @DaveUltra, yes please do! I think this is a good first issue that isn't too complicated to add. Are you familiar with Git? If so, just read this https://github.com/AnthonyCalandra/modern-cpp-features/blob/master/CONTRIBUTING.md before getting started and open a pull request when it's ready for review.

**Comment by DaveUltra** [comment]
Yes, I'm a bit familiar with Git, although I rarely use branches and submodules. I've been mostly working with private projects where I'm the only one developing.
I have opened a pull request, I hope my changes will fit into your project.

**Comment by AnthonyCalandra** [comment]
Merged.
