### ISSUE TITLE
Q: How to do template lambda expression immediately call in c++20 ?

### ISSUE THREAD

**Issue by Wyvern** [AnthonyCalandra/modern-cpp-features#76]
example:
```
auto f = []<typename T>(std::vector<T> v) {
  // ...
};
```
we use `f<int>(v)` to call function. `f` is a lambda function object.

if we want `f` is a value returned from this lambda expression immediately call, how to do?
```
auto f = []<typename T>(std::vector<T> v) {
  // ...
}<int>(v);
```
is this right? tried in online compiler but failed. What's the problem...

**Comment by AnthonyCalandra** [comment]
I don't believe it is currently possible to explicitly select a type for T in an IILE (immediately-invoked lambda expression) expression.

**Comment by Wyvern** [comment]
Thanks for your reply. 
Maybe that's right. Templated IILE is only supported when there is a default value for template argument.
````
auto f = []<typename T=int>(std::vector<T> v) {
  // ...
}(v);
```
Currently, there is  NO way to explicitly set template argument for T-IILE, hope to add it in future C++ 2x spec.

**Comment by AnthonyCalandra** [comment]
Closing issue since we've got our answer. :)
