### ISSUE TITLE
add C++17 lambda capture `this` by value to parallel C++11 capture `this` by reference

### ISSUE THREAD

**Issue by cdacamar** [AnthonyCalandra/modern-cpp-features#9]
Possibly after this section: https://github.com/AnthonyCalandra/modern-cpp-features#constexpr-lambda

syntax:
`auto l = [*this]{ some_member_fn(); };`

**Comment by AnthonyCalandra** [comment]
Thanks for the suggestion! I've added the section here: https://github.com/AnthonyCalandra/modern-cpp-features#lambda-capture-this-by-value.
