### ISSUE TITLE
C++ need help!!!

### ISSUE THREAD

**Issue by geekpranker** [AnthonyCalandra/modern-cpp-features#93]
Write a program that will display the following output.
Need some help.!!

https://imgur.com/sHANj3L

**Comment by AnthonyCalandra** [comment]
Hi there, I'm afraid this isn't the right place to ask for C++ help. I recommend posting on a forum or Q&A site for your question.

**Comment by geekpranker** [comment]
I am sorry, I'm just new. Thank you.
