### ISSUE TITLE
Missing char32_t, char16_t and misplace of char8_t.

### ISSUE THREAD

**Issue by Au-lit** [AnthonyCalandra/modern-cpp-features#94]
- `char8_t` is a fundamental type of C++20, not a library feature.
- `char16_t` and `char32_t` are fundamental types of C++11 (them also aren't library features).

**Comment by AnthonyCalandra** [comment]
Yes, I agree, looks like I put them in the wrong sections.

**Comment by AnthonyCalandra** [comment]
Addressed by d9b99892b0bbe0d57069f6d76899668e88e0a0dc
